global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'blackbox GET'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
     - targets:
       - dominio
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ipblackbox:port
